name: Run Python script
on:
  schedule:
    # 매 시간마다 실행 (UTC 기준)
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name : Install dependencies 
        run : |
          python -m pip install --upgrade pip
          pip install pandas geopy requests beautifulsoup4

      # Note that you would replace "user_location_gen_2.py" with the actual path to your .py file in the repository.
      
      - name : Run Python script 
        run : python xml_to_seoul_data_1.py

      # Check if seoul_data_temp.csv is created successfully.
      
      - name : List files in the current directory 
        run : ls
      
      # Commit and push if changes
      
      - name : Commit and push if changes 
        run : |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add seoul_data_temp.csv 
          git commit -m "Add updated csv file" && git push || echo "No changes to commit"
